### ISSUE TITLE
The link pointing to the current version of the specs doesn't work.

### ISSUE THREAD

**Issue by ifokkema** [fdp-specs/fdp-specs.github.io#4]
The [link in the specs](https://github.com/fdp-specs/fdp-specs.github.io/blob/c73fc1412496afbb22c4ce67ca960480f6e4b017/index.html#L46) that is supposed to link to the current version of the specs doesn't actually work.
Therefore, it's not possible to link to the used version of the specs in the `fdp-o:conformsToFdpSpec` property.

**Comment by luizbonino** [comment]
Fixed.
The index.html now only redirects to a page containing the specific version of the FDP specs. We have a page for v1.1 and for the old v1.0.
